### PR TITLE
Refactor Pursuit/switch and fix U-turn/drain move issues

### PR DESCRIPTION
**Pull request by itsdarsh**
This fix addresses part of #256

Drain moves base their recovery on the floor of 1/2 of wCurDamage (or 1, if only 1 damage was dealt). In base Crystal, there is code in the subtract HP function that sets wCurDamage to the original value of wPlayerMonHP/wEnemyMonHP before changing those values if the Pokemon takes more damage than it has remaining HP (in other words, set wCurDamage to what the Pokemon's HP was before it fainted). This fix re-implements that code, which will also make sure Pokemon take correct damage on recoil damage (which also bases its recoil damage on wCurDamage). This adds 32 cycles to each damage calculation.

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
This will not compile. Did you test it?

**Comment by itsdarsh** [comment]
Sorry! I typed it in by hand but I really should've copied and pasted it in. It should've been `ld [wCurDamage+1], a` at line 1926 and `ld [wCurDamage], a` at line 1929 but I forgot to put brackets in appropriately. It should compile now.

**Comment by FredrIQ** [comment]
If A uses U-Turn first, B responds with immediate Pursuit before the switch-out and is knocked out with Rocky Helmet, does things still work as they should?

**Comment by itsdarsh** [comment]
Probably not, I forgot all about Rocky Helmet fainting a Pursuit user (or similarly that user dying of Life Orb recoil). There's also a visual bug where the fainted opponent's HP bar will reload after you select a Pokemon if you knock out the enemy mon with U-turn. I'll definitely get the faint after Pursuit issue working, since that would also affect a switch out resulting from Teleport during a trainer battle (which calls ContinueToSwitchOut).

**Comment by itsdarsh** [comment]
PursuitSwitch no longer copies wLastPlayerMon to wCurBattleMon to run, removing a TODO

**Pull request merged**
