### PR TITLE
[9bit] Port all of SoupPotato's Pokémon sprite animations

### PR DESCRIPTION
**Pull request by etdv-thevoid**
**Addresses Issue #555** 

**Supersedes PR #626 (Outdated)**

---

Ports all of [SoupPotato's](https://github.com/SoupPotato) custom Pokémon sprite and animation work from [here](https://github.com/SoupPotato/pokecrystal_SpriteBase) (as of Sept. 2022).

Additionally, all sprite `.png` files have had a `palfix.py` pass to reduce their individual file size.

**Note:**
Pokémon with cosmetic forms in **PolishedCrystal** are excluded from this port _(i.e. Arbok, Pichu, Pikachu, Magikarp, Unown)_.

---

**ROM Free Space:**

| **Pre merge**    | **156444**  | **2097152** | **7.46%**  |
|:---------------- |:----------- |:----------- |:---------- |
| **Post merge**   | **133615**  | **2097152** | **6.37%**  |
| **Diff**         | **−22,829** | **±0**      | **−1.09%** |

### CODE REVIEW

**Comment by Rangi42** [comment]
Thanks a lot! I'll go over this to make them grayscale and remove some (e.g. Aipom). It's very helpful to have all the old and new front sprites side by side in a diff like this.

**Comment by FranktheMute** [comment]
Hello, any chance you can add the new Togekiss sprite as well? It was originally made by Brolunite and then I edited it further.

Here: https://imgur.com/a/Ivt1Aor

**Comment by Rangi42** [comment]
(Does this update every sprite, even the ones that weren't redrawn?)

**Comment by etdv-thevoid** [comment]
> (Does this update every sprite, even the ones that weren't redrawn?)

Just pushed another set of changes from running optimization on all of the `.png` files. They are all saved in grayscale now.

**Comment by etdv-thevoid** [comment]
With the new optimizations, sprites that were not edited by SoupPotato should not be picked up anymore in this PR.

**Comment by Rangi42** [comment]
Superseded by #733.

**Pull request closed without merging**
