### PR TITLE
Sprites & animations

### PR DESCRIPTION
**Pull request by flempa316**
Same PR as before, closed and reopened to allow for more branching on my fork of PC.

Animations for:
Alolan Geodude
Alolan Graveler
Alolan Golem
Alolan Marowak
Alolan Vulpix
Alolan Ninetales
Galarian Slowbro
Alolan Persian
Alolan Meowth
Galarian Weezing
Galarian Moltres

Back Sprites For:
Slowbro
Slowpoke
Vulpix

### CODE REVIEW

**Comment by Rangi42** [comment]
These are some good animations; thanks a lot!

A few issues:

- Marowak and Weezing have their dark and light hues swapped
- Articuno is not yet grayscale (I know it's a WIP)

**Comment by flempa316** [comment]
Thank you, appreciate it! And no problem, happy to help. 

I've swapped weezing and marowak light\darks. : )

**Comment by Rangi42** [comment]
Please restore the original Articuno anim0.asm and front.png so they won't get deleted when this merges.

**Comment by flempa316** [comment]
That should do it I believe. Let me know if not

**Comment by Rangi42** [comment]
Thanks for your patience! They're ready to merge :D

**Comment by flempa316** [comment]
Awesome!

**Pull request merged**
