### PR TITLE
Fix for bicycle and surf music in overcast areas.

### PR DESCRIPTION
**Pull request by VermilionCosmos**
Removed overcast music handling to restore bike and surf music in overcast areas.

### CODE REVIEW

**Comment by vulcandth** [comment]
Instead of deleting the overcast music handler code.. we should instead add a check for PlayerState to determine if the player is actively riding a bike or not.

**Comment by vulcandth** [comment]
Something like:

```asm
ld a, [wPlayerState]
and a
jr z, .check_special

```

`and a` checks if the register a is zero.. aka `PLAYER_NORMAL` (not surfing or biking).

**Comment by itsdarsh** [comment]
I'd like to know why it was added in the first place before merging this. There appears to be some intentionality behind the code as written.

**Comment by VermilionCosmos** [comment]
So the I am unsure if the player state needs to be checked because there is already functionality that just disables bike and surf music. The only thing that the Overcast Handler does is see if its Overcast, then run the GetMapMusic command which is only used for the purpose of turning off bike and surf music. I think its more that the Overcast Handler doesn't seem like it has a purpose right now, but maybe was meant to have one and left there, which ended up just removing functionality.

(I could be completely wrong, but this is my understanding.)

**Comment by VermilionCosmos** [comment]
To clarify, there is already a thing called "GetMapMusic" which only purpose is to disable surf and bike music. Overcast handler just seemed to be calling it, but had no special music of its own.

**Comment by Rangi42** [comment]
Yes, this code was intentional.

**Pull request closed without merging**
