### PR TITLE
Virtual Console for Polished Crystal 9bit

### PR DESCRIPTION
**Pull request by vulcandth**
This was done as sort of a thank you for @Rangi42, for the help and guidance in getting Virtual Console integrated with the pret repositories. 

Please reference the following for more information about the Virtual Console Integration:

pret/pokecrystal#813

pret/pokecrystal#882

[https://github.com/pret/pokecrystal/blob/master/docs/vc_patch.md](https://github.com/pret/pokecrystal/blob/master/docs/vc_patch.md)

Current information on the state of this PR:

*   ~~The Makefile changes were what was necessary for testing this feature; you will probably want to change things before merge. Currently as is, it allows your to specify any number of make commands followed by the `vc` command. For example: `make -j6 debug vc` will build a virtual console patch using debug as the base.~~
*   ~~`hSerialConnectionStatus` seems to be hardcoded by the VC emulator for the hook `[linkCable fake begin]`, and must be located at address `ffcb`. A `vc_assert` macro should be added somewhere in the code to verify it exists in the correct address. Although, if the intent is to fully support Virtual Console, you may want to change this to a normal assert.~~
*   ~~The CI Github Actions may or may not need to be adjusted. I haven't looked into that at all.~~
*   ~~Currently it appears VC Link Trading works fine.. other than the fact I noticed the palette for the debug Weezing changed after it was traded. (Need to test this in another emulator)~~
*   ~~VC Link Battling is a desync'd glitchfest. This needs to be looked at further. Also I need to test this more in another emulator to make sure its just the Virtual Console having issues.~~

TODO before Merge (Feel free to add additional tasks):

- [x] (EDGE CASE) Test trading an EGG and hatching it after.
- [x] Remove Patch/Hook padding requirement such as (`{hex @+1 4}` -> `{hex @+1}`)
- [x] Rename some patch labels to be more intuitive.
- [ ] (Glitch - All Emulators) Address "Waiting..." Graphical glitch

Feel free to make changes to this PR if you would like to work on it with me, or feel free to close it if you decide you don't want to integrate it. No hurt feelings for me. :) 

I will continue to update this PR as I have free time to work on it and test certain features.

### CODE REVIEW

**Comment by Rangi42** [comment]
@vulcandth Thank you so much for contributing this!

I made a few updates, including:

- Add the `vc_assert` for `[hSerialConnectionStatus` that we'll eventually add to pret
- Remove the fake Stadium data patch
- Add a fake patch for the 9bit alpha build timestamp
- De-optimize the code so the `linkCable_block_input2` patch can work

I have *not* verified that all the patches/hooks are correct. Some may still be like `linkCable_block_input2`, potentially invalid due to code changes, or not even patching the correct byte any more. Those will need testing to verify they work for Wi-Fi trading and battling.

**Comment by vulcandth** [comment]
Issues with Link Battles have been resolved. Ready for review and feedback.

**Comment by Rangi42** [comment]
I've updated the CI to build and upload the patches. If Wi-Fi trading and battling definitely work, then this is ready to merge!

**Comment by vulcandth** [comment]
@Rangi42 battling definitely works now. Trading seems to work just fine..  however if there are certain edge cases in mind you would like test, i'd be happy to test on actual hardware for you.

**Comment by Rangi42** [comment]
These patches from pokecrystal are not present for Polished Crystal. Documenting why they aren't needed:

Do we need to add these?
- `[fight begin]`
- `[FPA link fight begin]`
- `[FPA link fight End0]`
- `[FPA link fight End1]`
- `[FPA link fight End2]`
- `[FPA link fight End3]`
- `[FPA link fight End4]`

Time Capsule patches:
- `[Network358]`
- `[Network359]`
- `[Network364]`
- `[NetworkDelay1]`
- `[NetworkDelay2]`
- `[to_play2_mons1]`

SGB border patch:
- `[Network_RESET]`

Celebi event patch:
- `[BiographySave_ret]`

GB Printer patches:
- `[print forbid 1]`
- `[print forbid 2]`
- `[print forbid 3]`
- `[print forbid 4]`
- `[print forbid 5]`

Mystery Gift patches:
- `[infrared fake 0]`
- `[infrared fake 1]`
- `[infrared fake 2]`
- `[infrared fake 3]`
- `[infrared fake 4]`

Flashing move animation patches:
- `[FPA 001 Begin]`
- `[FPA 002 Begin]`
- `[FPA 003 Begin]`
- `[FPA 004 Begin]`
- `[FPA 005 Begin]`
- `[FPA 006 Begin]`
- `[FPA 007 Begin]`
- `[FPA 042801 Begin]`
- `[FPA 001 End]`

**Comment by vulcandth** [comment]
Something I thought might be worth mentioning; This is a graphical glitch during link battles where the "Please wait" popup box that appears over the other windows that displays whenever the game is waiting for the other player to select a move, doesn't fully go away (instead gets glitched in the background). IIRC, this occurred in all emulators I tested using the DEBUG build. It could be an issue limited to debug, as I did not test any other builds. If its something super simple to fix, then we should try to fix it here.. if not; it can wait to later... It really doesn't effect the gameplay at all, its really is minor. I'll post screenshots later when I get home.

Have you seen this before @FredrIQ ?

**Comment by Rangi42** [comment]
> There is a graphical glitch during link battles where the "Please wait" popup box that appears over the other windows that displays whenever the game is waiting for the other player to select a move, doesn't fully go away (instead gets glitched in the background).

This occurs in a debug build on BGB; I expect it happens in non-debug too.

image

**Comment by vulcandth** [comment]
The issues I was talking about: You can see the remnants of the Waiting box over the bottom mewtwo.
image

**Comment by vulcandth** [comment]
I obtained the Odd Egg and traded it using the Virtual Console to another system... ran around for a while and it hatched normally into a shiny igglybuff... Oh; and yeah the second system I was testing on.. I chose Rangi42 as the Trainer name lol.

**Comment by vulcandth** [comment]
@Rangi42 I recommend we hold this PR open until https://github.com/pret/pokecrystal/pull/906 and https://github.com/pret/pokecrystal/pull/907 is merged or close to being merged. As I plan to port the comments/patch names to this PR when i'm done.

**Comment by vulcandth** [comment]
Patches have been renamed using the aliases from pokecrystal. Ready for merge.

**Pull request merged**
