### PR TITLE
Updated Arboks

### PR DESCRIPTION
**Pull request by SoupPotato**
Added the new arboks. The images will need to be png crushed however.

### CODE REVIEW

**Comment by Rangi42** [comment]
utils/palfix.py will do it.

**Comment by Rangi42** [comment]
Shouldn't Agatha's still have red eyes?
image

**Comment by SoupPotato** [comment]
hmm I was going with this image
Prof _Oak's_Pokemon_Lecture_Arbok_3
but if you want red eyes i can

**Comment by Rangi42** [comment]
Oh, it was in the anime too? That's fine then.

**Pull request merged**
