### PR TITLE
Add build script

### PR DESCRIPTION
**Pull request by jagger27**
Adds a build script that builds a "nightly" release on push to master. It automatically prunes the last release tagged as `nightly`.

### CODE REVIEW

**Comment by Rangi42** [comment]
`uses: jagger27/delete-release@master` should refer to `Rangi42`.

**Comment by Rangi42** [comment]
Also, please append `$GITHUB_SHA` (the commit hash) to the ROM names so users can identify where it came from.

**Comment by jagger27** [comment]
> `uses: jagger27/delete-release@master` should refer to `Rangi42`.

You would need to fork [jagger27/delete-release](https://github.com/jagger27/delete-release) if you want that. As it is, it's reusable action to delete a release. I added the SHA suffix. That environment value keeps the long hash, mind you, so it's a bit ugly.

**Comment by Rangi42** [comment]
Thanks! `jagger27/delete-release@master` is fine then.

You're right about the long hashes; `${GITHUB_SHA::8}` evaluates to the first 8 characters.

**Comment by jagger27** [comment]
Alright, should be good to go! Sorry for the commit spam. Gotta make a commit every time I test the build rule. Once it's in this repo the hash will actually match the commit.

**Pull request merged**
