### PR TITLE
Hidden grottoes

### PR DESCRIPTION
**Pull request by flempa316**
Hidden Grottos added throughout Johto, some tileset tweaks to accommodate cave grottos and pink tree grottos.

### CODE REVIEW

**Comment by Rangi42** [comment]
Please rebase this to `master` to use the updated label and macro names.

**Comment by flempa316** [comment]
Can do

**Comment by flempa316** [comment]
I believe those are the only files that needed to be rebased @Rangi42, let me know if there is anything else!

**Comment by Rangi42** [comment]
These have been implemented in 9bit.

**Pull request closed without merging**
